.build_artifact:
  stage: build_artifact
  image: oven/bun:${BUN_IMAGE_TAG}
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${APP_NAME}
    paths:
      - node_modules/
      - app/${APP_NAME}/node_modules/
  before_script:
    - bun install
  script:
    - bun run build --filter ./app/${APP_NAME}
  artifacts:
    paths:
      - app/${APP_NAME}/${BUILD_DIR_NAME}
    expire_in: 1 hour

.build_image:
  stage: build_image
  image: docker:${DOCKER_IMAGE_TAG}
  services:
    - docker:${DOCKER_IMAGE_TAG}
  variables:
    IMAGE_TAG: ${AWS_ECR_REPOSITORY}/${APP_NAME}:${APP_VERSION}
  script:
    - docker build -f docker/Dockerfile.app.${APP_NAME} -t ${IMAGE_TAG} app/${APP_NAME}
    - mkdir -p docker-images
    - docker save ${IMAGE_TAG} -o docker-images/${APP_NAME}.tar
  artifacts:
    paths:
      - docker-images/${APP_NAME}.tar
    expire_in: 1 hour

.upload_image:
  stage: upload_image
  image: docker:${DOCKER_IMAGE_TAG}
  services:
    - docker:${DOCKER_IMAGE_TAG}
  before_script:
    - apk add --no-cache aws-cli
    - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
    - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
    - aws configure set default.region ${AWS_REGION}
    - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
  script:
    - docker load -i docker-images/${APP_NAME}.tar
    - docker tag ${AWS_ECR_REPOSITORY}/${APP_NAME}:${APP_VERSION} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REPOSITORY}:${APP_NAME}.${APP_VERSION}
    - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REPOSITORY}:${APP_NAME}.${APP_VERSION}
  after_script:
    - docker rmi ${AWS_ECR_REPOSITORY}/${APP_NAME}:${APP_VERSION} || true
    - docker rmi ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REPOSITORY}:${APP_NAME}.${APP_VERSION} || true
